language: node_js
os: linux
dist: xenial
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: 14
      deploy:
        provider: npm
        email: rogier+npm@konfirm.eu
        on:
          branch: master
          tags: true
        api_key:
          secure: bXfwTp0tv5s5OKforPAKWvZPXWv/ho24txYT64SsreKyCk1ljZ2SO7QqPY7dSzLRZ/uun6yk6UQKHRTe9hU/jF2FxRABsOLUZsPtQGPlbR7DAuGFpvvXe68DG9K4heZKyzVhaQFA1uwXWjism0bmEZbS9sKFxiiI+NhHVgx6R8O8Ver/Ds4YyZjeDF+KZz7UcbtsmP4BVGAMjS+V7D5PcWEwI6YI/h/cSRa6OV3APafR0lXnHCB2Lp7aWGuz9UnW+3wVYckqxh6+SrqOPHaCWEn5SGskI292RITC+ca21dK6G/9hrIfEV2TKZFqVGiZ2CsJn0mM5hzn7MHNxiu30rwKf8dYRQfyT0sarYyqeFpNM4x25NKn73Gu6AUc7RDhlYmCd7+EkAAuV8tkXmrARrFYImv2IXRR5WDzM5W6QNeyh/RYPGstCPmW+fqv2jT+89YYqcY814A2xnBHl5mOgQj1xEaBzZ7oJEc2OD1PcK3ThUe+iy+j+OuSjL4PptG9sxZWg5vxUa0jcWkaO9UXo5MPkENXeypUTBmXoIUY68Fc3a1dIX+QMwjMVmHoJegHEYqXDu6sUdx7QA6bSbUckfDEig9HNqUpOE9yoycFAHYgMoTfO+r2RfQrxVh86/S0/pDbHqW9O9HbhuUECuEbb5vJGY3+n/VkBTGBSKoesLPI=
