language: node_js
node_js:
    - '7'
    - '8'
    - '9'
    - '10'
    - '11'
    - '12'

jobs:
    include:
        - stage: npm release
          if: tag IS present
          node_js: 12
          deploy:
              provider: npm
              email: rogier+npm@konfirm.eu
              on:
                  branch: master
                  tags: true
              api_key:
                  secure: FGzO2Kw6Xg48ZlCwg1+ftvDRUQq6Ducauiy+GCvZK/V3Mo4x8DMjXo2ElGV976SDHECACT1OvYjtjdAiAdoseVwAVwzTI5uiSiT5JH7JcNJOIrqLbcy9CJvsQ3aBO2fXpdXW2jtHCWGGKfGYKfHNyeluoPEQyY7BCuoQFhDl1pVdgxkMMyE8woL4Xgl6/OVrhPtSBFmAIeMmo5/bIq5jzeatTc0AB8Uf0wW9qSFniiCZlLPjbYKHNYQci54eyWk4HaUbVlv4Fj82zy+3KnnZzj4X4kFDWX1/1gaGgP7MwqP9FxZI/DOoZxDGKEF4TM7Clxr6IH47/MTdQD40M1UJ7Qsb33OJx9EnQRt8DJgI3NR/QWg+r/QjltoDRqZ24NEygJDBDkDiXc7gjZqCnEyGwfWZUhEA3ZXMsRyoLJNpu27CykAaJXsu5oUEQJWwQsH9+bKftBXJg3rgsvk4wZIcMu9UzPzhafKIj2PfsN7HT1yXcdQvWNGLwlkgyzAs7llXPF4p/cravY551nT/vLeJCsrHzXU3S7W1ubXKNY96RNBPg+wwJPtwdL4nsen+5Q9Lz+P8PrbKCW/bLONFhjqnmGw/Xq81+dy+Eyguk47OsE4xQH+Hao6YeSPn1h+hC+PQyzLp2RvwwcmGf/ejap5Pxr/1wpGl+MMjG4zqFyDr+Y0=
